name: Deploy - Dev Current

on:
  workflow_dispatch:
  # push:
  #   branches: [current]
  #     paths-ignore: 
  #     - '.github/workflows/*'
  
jobs:
  deploy:
    name: Dev Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run more steps from the Current branch
        run: echo Current, world!
